### ISSUE TITLE
Problem with combined variable declaration / assignment inside procedure

### ISSUE THREAD

**Issue by HugoPlatzer** [cksystemsteaching/CC-Summer-2016#96]
I just found out the following program compiles without errors with selfie, but returns 0:

```c
int main() {
  int x = 1;
  return x;
}
```

I can see from the grammar.md file that this combined declaration/assignment is only supported for global variables, but why is the compiler not complaining?

**Comment by HugoPlatzer** [comment]
Didn't see the warning message before the mipster stats :)

It's just a little weird that despite an incorrect program, it still generates code...

**Comment by ckirsch** [comment]
Thank you for pointing out this issue. Error handling in starc is very basic. The goal is to report as many errors as possible without stopping compilation. It's true that in the presence of errors starc should not generate code. You are welcome to re-open the issue and propose a fix in a pull request. If you do then please try to reason first about which error and warning situations are possible in starc and decide what to do in each situation before coding anything. I can think of at least three scenarios: 1. warnings should not prevent code generation, 2. some errors lead to exit() calls terminating selfie, not just starc, and 3. the remaining errors allow starc to continue. You should probably only address 3. and only check if 1. and 2. keep working as they are supposed to. Situation 2. can also improve by reducing the number of times starc exits but this is a different problem.
